### ISSUE TITLE
CONS2 dates issue

### ISSUE THREAD

**Issue by acadogan** [MoonRaker/cons2-python#1]
Hey Derek,

We're having a couple issues  with the CONS2 program.  When we run the program following all steps laid out in the documentation it only gives us data for the first year and in the log states "WARNING  Missing years of weather data." For example: if we choose the year range of 2010-2016 it only gives us the numbers for 2010.  When we change the year range to 2011-2016 then we get no outputs and the same warning.  However, if we put the range as 2010-2010 then it will give data for just that year plus the warning. If only 2010 data is provided and the year range is 2010 then everything runs correctly. If only 2011 data is provided and the year range is 2011 no results and the warning appear. So it seems like there is something going on the prevents any outputs past the year 2010.

Any help would be greatly appreciated,

Ammon Cadogan

**Comment by MoonRaker** [comment]
Found and corrected the issue (commit https://github.com/MoonRaker/cons2-python/commit/4840130596997b9ae5d4124f1677ce14e44c6fff). Thanks for catching this. You can find the updated binary in release 4.1 https://github.com/MoonRaker/cons2-python/releases/tag/v4.1
